import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create fgdf App",
  description: "Generated by create fgdf app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className='antialiased'>
        <div>{children}</div>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
